url: http://www.micronfcboard.com
baseurl: /

# Site settings
title: MicroNFCBoard - NFC made easy
company: AppNearMe Ltd
email: contact@appnearme.com
description: "MicroNFCBoard - NFC made easy; read and write tags, transfer data with NFC phones"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/AppNearMe
  - title: github
    url: http://github.com/AppNearMe

# Distributors
distributors:
  - name: SeeedStudio
    image: seeedstudio.png
    link: http://www.seeedstudio.com/depot/MicroNFCBoard-p-2431.html

# Postal address (add as many lines as necessary)
address:
  - line: ideaSpace
  - line: 3 Charles Babbage Rd
  - line: Cambridge
  - line: UK

# Build settings
markdown: kramdown
permalink: pretty
